package com.DriveX.DriveX.model.vehicle;

public enum Brand {

    FERRARI, LAMBORGHINI, PORSCHE, MASERATI, BENTLEY, ROLLS_ROYCE,
    MCLAREN, PAGANI, KOENIGSEGG, LOTUS, ASTON_MARTIN, BUGATTI,

    AUDI, BMW, MERCEDES, VOLKSWAGEN, OPEL, RENAULT, PEUGEOT, CITROEN,
    FORD, TOYOTA, HONDA, NISSAN, MAZDA, SUBARU, HYUNDAI, KIA, FIAT,
    SEAT, SKODA, DACIA, ALFA_ROMEO, JAGUAR, LAND_ROVER, CHEVROLET,
    CHRYSLER, JEEP, GMC, CADILLAC, MINI, INFINITI, ACURA, BUICK,
    LINCOLN, TESLA, MITSUBISHI, SUZUKI,

    YAMAHA, KAWASAKI, DUCATI, KTM, TRIUMPH, HARLEY_DAVIDSON, INDIAN,
    ROYAL_ENFIELD, APRILIA, MOTO_GUZZI, BAJAJ, VICTORY, CAN_AM,
    ZERO, BMW_MOTORRAD, CFMOTO, SHERCO, SYM, MALAGUTI, BETA, GAS_GAS,
    HUSABERG, KYMCO, RIEJU, MONTESA, OSSA, BIMOTA, CAGIVA, LAVERDA,
    VESPA, ITALJET, MONDIAL, PEUGEOT_SCOOTERS, APRILIA_MOTO, MBK,
    KTM_RC, BETA_MOTORCYCLES, ZERO_MOTORCYCLES,

    MG, SMART, ALPINE, DS, PLYMOUTH, SAAB, SCION, DAIHATSU, HOLDEN,
    TATA, PROTON, PERODUA, LADA, GEELY, CHERY, GREAT_WALL, MAHINDRA,
    ZOTYE, FISKER, RIMAC, LUCID, POLESTAR, BYD, NIO, XPENG,

    PONTIAC, OLDSMOBILE, PACKARD, STUDEBAKER, HUMMER, DELOREAN,
    VECTOR, SINGER, FACEL_VEGA, TVR, BRISTOL, MORGAN, CATERHAM,
    GINETTA, ROVER, AUSTIN, HILLMAN, SUNBEAM, TALBOT, SIMCA, DATSUN;
}